services:
  - type: web
    name: haas-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn haas_backend.app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /api/users/test
